# Generated by Django 4.1.1 on 2022-10-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='user_courses',
        ),
    ]
