# Generated by Django 4.1.1 on 2022-10-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0002_user_course_delete_user_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course_detail',
        ),
        migrations.DeleteModel(
            name='user_course',
        ),
        migrations.DeleteModel(
            name='user_logins',
        ),
        migrations.DeleteModel(
            name='user_reg',
        ),
    ]
