# Generated by Django 4.1.1 on 2022-10-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interapp.user_course'),
        ),
    ]
