# Generated by Django 4.1.1 on 2022-10-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0005_alter_course_detail_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='duaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='course_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interapp.duaration'),
        ),
    ]
