# Generated by Django 4.1.1 on 2022-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='DOB',
            field=models.DateField(),
        ),
    ]
