# Generated by Django 4.1.1 on 2022-09-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials_app', '0002_alter_register_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
