# Generated by Django 4.1.1 on 2022-09-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials_app', '0003_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='fname',
            new_name='firstname',
        ),
    ]
