# Generated by Django 4.1.1 on 2022-09-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials_app', '0004_rename_fname_register_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='DOB',
            field=models.DateField(default='1997-01-01'),
        ),
    ]
