# Generated by Django 4.1.1 on 2022-09-26 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials_app', '0006_user_reg_delete_login_delete_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_reg',
            old_name='DOB',
            new_name='dob',
        ),
    ]
