# Generated by Django 4.1.1 on 2022-09-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials_app', '0007_rename_dob_user_reg_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='email',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
