# Generated by Django 4.1.1 on 2022-09-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials_app', '0008_alter_user_reg_address_alter_user_reg_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
