# Generated by Django 4.1.1 on 2022-09-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials_app', '0009_alter_user_reg_address_alter_user_reg_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
