# Generated by Django 4.1.1 on 2022-09-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials_app', '0013_alter_user_reg_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
