# Generated by Django 4.1.1 on 2022-09-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials_app', '0014_user_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_login',
        ),
    ]
