# Generated by Django 4.1.1 on 2022-09-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials_app', '0015_delete_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
