# Generated by Django 4.1.1 on 2022-09-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials_app', '0016_alter_user_reg_dob_alter_user_reg_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
